### ISSUE TITLE
第8题为什么arr2 + 3, 10, 2不是斐波那契

### ISSUE THREAD

**Issue by night3759** [LearningInfiniTensor/learning-cxx#4]
请问一下【1, 7, 2, 11, 3, 18, 5, 29, 8, 47】，隔2取为【1， 2， 3， 5， 8】，这个为什么不是斐波那契

**Comment by zhouyecs** [comment]
这里的10表示能否找到长度为10的斐波那契数列

**Comment by pai2shub** [comment]
长度 10，指的是 斐波那契 数列的长度为 10
