### ISSUE TITLE
第30题答案的顺序问题

### ISSUE THREAD

**Issue by JasonZhaoWW** [LearningInfiniTensor/learning-cxx#5]
在wsl中第一个答案可以通过测试，第二个答案无法通过，在Windows中，第一答案不能通过测试，但是第二个可以。
依照逻辑来说第二个才是正常的顺序，请问为什么会出现这样的差异呢？
![答案1](https://github.com/user-attachments/assets/21f47cea-a102-45ce-ad57-595986911f7c)
![答案2](https://github.com/user-attachments/assets/73aa04f7-4a10-4b2c-875e-792ab03e2000)

**Comment by YdrMaster** [comment]
是的，析构顺序平台相关，此事在[冬季 QA](https://github.com/LearningInfiniTensor/.github/blob/main/qa/doc-2024w.md)已有记载
